name: fortran-src-extras
version: 0.1.0
synopsis: Common functions and utils for fortran-src.
description: Various utility functions and orphan instances which may be useful when using fortran-src.
category: Language
github: camfort/fortran-src-extras
license: Apache-2.0
maintainer: thefirstmuffinman@gmail.com

extra-source-files:
- README.md

dependencies:
- aeson >= 1.2.3.0
- base >= 4.7 && <5
- binary >= 0.8.5.1
- containers >= 0.5.0.0
- directory >= 1.3.0.2
- filepath >= 1.4.1.2
- fortran-src >= 0.2.1.1.0.3
- GenericPretty >= 1.2.1
- text >= 1.2.2.2
- bytestring >= 0.10.8.1
- uniplate >= 1.6.10
- optparse-applicative >= 0.14

library:
  source-dirs: src

tests:
  fortran-src-extras-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
    - fortran-src-extras
    - hspec
    - silently
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
