name: fortran-src-extras
version: 0.5.0
synopsis: Common functions and utils for fortran-src.
description: Various utility functions and orphan instances which may be useful when using fortran-src.
category: Language
github: camfort/fortran-src-extras
license: Apache-2.0
maintainer: thefirstmuffinman@gmail.com

extra-source-files:
- README.md
- CHANGELOG.md
- test/input_data/**/*

# 2022-01-25: raehik: the essentials + handful of syntax (most in GHC2021)
# 2022-06-21: copied from fortran-src 6702ee51cf7c0df5007e165003f053baa65706c1
default-extensions:
# essential
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
- PolyKinds
- LambdaCase
# deriving-related
- DerivingStrategies
- StandaloneDeriving
- DeriveAnyClass
- DeriveGeneric
- DeriveDataTypeable
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveLift
# less essential but still gimmes
- BangPatterns
- TupleSections

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && <5
- fortran-src >= 0.14 && < 0.16
- aeson >= 1.5 && < 2.2
- bytestring >= 0.10 && < 0.12
- optparse-applicative >= 0.14 && < 0.18
- uniplate ^>= 1.6.10
- GenericPretty ^>= 1.2.1
- text >= 1.2 && < 2.1
- containers >= 0.5 && < 0.7
- Diff >= 0.4.0

library:
  source-dirs: src
  dependencies:
  - filepath ^>= 1.4.1.2
  - either ^>= 5.0.0

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    build-tools:
    - hspec-discover
    dependencies:
    - fortran-src-extras
    - hspec >= 2.2 && < 3
    - silently ^>= 1.2
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

executables:
  fortran-src-extras:
    source-dirs: app
    main: Main.hs
    dependencies:
    - fortran-src-extras
    - yaml ^>= 0.11.8.0
