name: fortran-src-extras
version: 0.3.0
synopsis: Common functions and utils for fortran-src.
description: Various utility functions and orphan instances which may be useful when using fortran-src.
category: Language
github: camfort/fortran-src-extras
license: Apache-2.0
maintainer: thefirstmuffinman@gmail.com

extra-source-files:
- README.md
- CHANGELOG.md

# 2022-01-25: raehik: the essentials + handful of syntax (most in GHC2021)
# 2022-06-21: copied from fortran-src 6702ee51cf7c0df5007e165003f053baa65706c1
default-extensions:
# essential
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
- PolyKinds
- LambdaCase
# deriving-related
- DerivingStrategies
- StandaloneDeriving
- DeriveAnyClass
- DeriveGeneric
- DeriveDataTypeable
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveLift
# less essential but still gimmes
- BangPatterns
- TupleSections

dependencies:
- base >= 4.7 && <5
- fortran-src >= 0.9.0
- uniplate >= 1.6.10
- either ^>= 5.0.0

library:
  source-dirs: src
  dependencies:
  - aeson >= 1.2.3.0
  - binary >= 0.8.5.1
  - containers >= 0.5.0.0
  - directory >= 1.3.0.2
  - filepath >= 1.4.1.2
  - GenericPretty >= 1.2.1
  - text >= 1.2.2.2
  - bytestring >= 0.10.8.1
  - optparse-applicative >= 0.14

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    build-tools:
    - hspec-discover
    dependencies:
    - fortran-src-extras
    - hspec >= 2.2 && < 3
    - silently >= 1.2 && < 1.3
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
